"""Sync the canonical soul to all mirrors, or check for drift.

Usage (from the fable-soul skill root):
    python scripts/sync_soul.py          # sync everything
    python scripts/sync_soul.py --check  # report drift, change nothing
"""
from __future__ import annotations

import filecmp
import shutil
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[1]
CANONICAL = SKILL_ROOT / "references" / "soul.md"
# Global files get the compact rendering (same rules, table, and red flags;
# mechanisms and examples live only in canonical). Parity is checked below.
COMPACT = SKILL_ROOT / "references" / "soul-compact.md"
HOME = Path.home()

SKILL_MIRRORS = [
    HOME / ".claude" / "skills" / "fable-soul",
    HOME / ".codex" / "skills" / "fable-soul",
]

# Global files = target-specific header + soul body (from the "spirit" line onward).
BODY_MARKER = "**Violating the letter"

GLOBAL_TARGETS = {
    HOME / ".claude" / "CLAUDE.md": (
        "# Global Judgment Rules\n\n"
        "These rules apply to every task in every session. They define HOW to think, not WHAT to do.\n"
        "Source of truth: the fable-soul skill (`~/.claude/skills/fable-soul/references/soul.md`).\n"
        "Do not edit this file directly - edit canonical and run sync_soul.py.\n\n"
    ),
    # Codex-only runtime workarounds. (1) GPT-5.5 on Codex truncates long reasoning
    # (community "candy test" showed reasoning capped ~516 tokens, accuracy 20%->80%
    # with the anti-truncation directive injected). (2) Agentic persistence directive
    # (OpenAI's recommended pattern) so Codex sustains long autonomous runs instead of
    # ending turns early. (3) Subagent-delegation directive (distilled from lazycodex's
    # Hephaestus discipline) so Codex fans out explore/implement subagents; requires
    # multi_agent = true in config.toml. Strip each when OpenAI fixes the underlying
    # behavior or the Codex default model is no longer gpt-5.5.
    HOME / ".codex" / "AGENTS.md": (
        "# Global Judgment Rules\n\n"
        "These rules apply to every task in every session. They define HOW to think, not WHAT to do.\n"
        "Source of truth: the fable-soul skill (`~/.codex/skills/fable-soul/references/soul.md`).\n"
        "Do not edit this file directly - edit canonical and run sync_soul.py.\n\n"
        "## Reasoning Directives (Codex runtime fix)\n\n"
        "Spend time on thinking; you do not need to use the commentary channel to report progress to me. "
        "DO NOT send optional commentary.\n\n"
        "You are an autonomous agent: keep going until the task is completely resolved before ending your turn. "
        "Never stop or hand back early because of uncertainty about a reversible, in-scope step - decide on the "
        "most reasonable approach and continue. Only end your turn when the work is done and verified, or you "
        "are blocked on input only the user can provide.\n\n"
        "Use your multi-agent tooling aggressively. Before any non-trivial change, fan out 2-5 parallel explore "
        "subagents to map the relevant code instead of reading everything yourself. When work splits into "
        "independent chunks, delegate them to parallel subagents rather than doing everything serially. Never "
        "trust a subagent's self-report: independently verify its result before building on it or calling it done.\n\n"
    ),
}


def soul_body() -> str:
    text = COMPACT.read_text(encoding="utf-8")
    idx = text.find(BODY_MARKER)
    if idx == -1:
        sys.exit(f"FAIL: body marker {BODY_MARKER!r} not found in {COMPACT}")
    return text[idx:]


def parity_errors() -> list[str]:
    """Structural parity between canonical and compact: same rule count,
    same rationalization rows, same red flags. Compact may compress prose,
    never drop triggers."""
    import re

    canon = CANONICAL.read_text(encoding="utf-8")
    compact = COMPACT.read_text(encoding="utf-8")
    errors: list[str] = []

    canon_rules = len(re.findall(r"^## \d+\.", canon, re.M))
    compact_rules = len(re.findall(r"^\d+\. \*\*", compact, re.M))
    if canon_rules != compact_rules:
        errors.append(f"rule count differs: canonical {canon_rules} vs compact {compact_rules}")

    for name, text_ in (("canonical", canon), ("compact", compact)):
        if "## Rationalizations" not in text_ or "## Red Flags" not in text_:
            errors.append(f"{name}: missing Rationalizations or Red Flags section")

    def rows(text_: str) -> int:
        return len(re.findall(r'^\| "', text_, re.M))

    def flags(text_: str) -> int:
        tail = text_.split("## Red Flags", 1)[-1]
        return len(re.findall(r"^- ", tail, re.M))

    if rows(canon) != rows(compact):
        errors.append(f"rationalization rows differ: canonical {rows(canon)} vs compact {rows(compact)}")
    if flags(canon) != flags(compact):
        errors.append(f"red flag count differs: canonical {flags(canon)} vs compact {flags(compact)}")
    return errors


def render_global(header: str) -> str:
    return header + soul_body()


def dir_drift(mirror: Path) -> list[str]:
    """Files that differ or are missing between the skill root and a mirror."""
    drifted: list[str] = []
    sources = [p for p in SKILL_ROOT.rglob("*") if p.is_file() and "__pycache__" not in p.parts]
    for src in sources:
        rel = src.relative_to(SKILL_ROOT)
        dst = mirror / rel
        if not dst.exists() or not filecmp.cmp(src, dst, shallow=False):
            drifted.append(str(rel))
    for dst in mirror.rglob("*") if mirror.exists() else []:
        if dst.is_file() and "__pycache__" not in dst.parts:
            rel = dst.relative_to(mirror)
            if not (SKILL_ROOT / rel).exists():
                drifted.append(f"{rel} (extra in mirror)")
    return drifted


def main() -> None:
    check_only = "--check" in sys.argv
    problems: list[str] = []

    parity = parity_errors()
    if parity:
        for p in parity:
            print(f"PARITY: {p}")
        sys.exit("FAIL: compact rendering out of parity with canonical - fix soul-compact.md first")

    for mirror in SKILL_MIRRORS:
        drifted = dir_drift(mirror)
        if drifted:
            if check_only:
                problems.append(f"{mirror}: {', '.join(drifted)}")
            else:
                for rel in [d for d in drifted if "(extra in mirror)" not in d]:
                    dst = mirror / rel
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(SKILL_ROOT / rel, dst)
                print(f"synced skill -> {mirror} ({len(drifted)} file(s))")
        else:
            print(f"ok: {mirror}")

    for target, header in GLOBAL_TARGETS.items():
        expected = render_global(header)
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current and not current.startswith("# Global Judgment Rules"):
            print(f"SKIPPED {target}: existing content not generated by this script. "
                  f"Merge the soul body manually or remove the file first.")
            continue
        if current != expected:
            if check_only:
                problems.append(f"{target}: body or header differs from canonical")
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(expected, encoding="utf-8", newline="\n")
                print(f"regenerated {target}")
        else:
            print(f"ok: {target}")

    if problems:
        print("\nDRIFT DETECTED:")
        for p in problems:
            print(f"  - {p}")
        sys.exit(1)
    if check_only:
        print("all mirrors in sync")


if __name__ == "__main__":
    main()
