"""Sync the canonical soul to all mirrors, or check for drift.

zhenheco fork: instead of overwriting global instruction files, this script
injects marker-delimited blocks into the CC Cli vault sources:

  - CLAUDE-global.md  <- compact soul block (Claude reads it via the
    ~/.claude/CLAUDE.md symlink; Codex inherits it because sync-codex.sh
    concatenates CLAUDE-global.md + codex-tail.md into ~/.codex/AGENTS.md)
  - codex-tail.md     <- Codex-only Reasoning Directives block

Skill mirror is the vault skills dir (~/.claude/skills symlinks there);
a per-skill symlink is ensured for ~/.codex/skills, matching the existing
per-skill pattern. After injection, sync-codex.sh regenerates AGENTS.md.

Usage (from the fable-soul skill root):
    python scripts/sync_soul.py          # sync everything
    python scripts/sync_soul.py --check  # report drift, change nothing
"""
from __future__ import annotations

import filecmp
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Callable, Optional

SKILL_ROOT = Path(__file__).resolve().parents[1]
CANONICAL = SKILL_ROOT / "references" / "soul.md"
# Global files get the compact rendering (same rules, table, and red flags;
# mechanisms and examples live only in canonical). Parity is checked below.
COMPACT = SKILL_ROOT / "references" / "soul-compact.md"
HOME = Path.home()
VAULT = Path(os.environ.get("CC_VAULT", HOME / "Documents" / "CC Cli"))

# Single skill mirror: the git-synced vault. ~/.claude/skills is a symlink to
# the vault skills dir; ~/.codex/skills gets a per-skill symlink (ensured below).
SKILL_MIRRORS = [
    VAULT / "skills" / "fable-soul",
]
CODEX_SKILL_LINK = HOME / ".codex" / "skills" / "fable-soul"

# Compact soul body = everything from the "spirit" line onward.
BODY_MARKER = "**Violating the letter"

BEGIN_MARK = "<!-- fable-soul:begin (generated by sync_soul.py - edit canonical soul.md, never this block) -->"
END_MARK = "<!-- fable-soul:end -->"

# Regenerates ~/.codex/AGENTS.md from CLAUDE-global.md + codex-tail.md.
POST_SYNC_HOOK: Optional[Path] = VAULT / "scripts" / "sync-codex.sh"


def soul_body() -> str:
    text = COMPACT.read_text(encoding="utf-8")
    idx = text.find(BODY_MARKER)
    if idx == -1:
        sys.exit(f"FAIL: body marker {BODY_MARKER!r} not found in {COMPACT}")
    return text[idx:]


def render_soul_block() -> str:
    header = (
        "---\n"
        "**F · 判斷層 / Fable Soul Judgment Layer**\n\n"
        "Source of truth: `$HOME/Documents/CC Cli/skills/fable-soul/references/soul.md`"
        "（dev repo: `zhenheco/fable-soul`）。以下為 compact rendering，由 sync_soul.py 生成——"
        "改 canonical 後跑 sync，勿手改本區塊。\n\n"
    )
    return f"{BEGIN_MARK}\n{header}{soul_body().rstrip()}\n{END_MARK}\n"


def render_codex_block() -> str:
    # Codex-only runtime workarounds (NOT part of the soul). Strip each when
    # OpenAI fixes the underlying behavior or the Codex default model moves
    # off gpt-5.5. Rationale: references/maintenance.md.
    directives = (
        "## Reasoning Directives (Codex runtime fix)\n\n"
        "Spend time on thinking; you do not need to use the commentary channel to report progress to me. "
        "DO NOT send optional commentary.\n\n"
        "You are an autonomous agent: keep going until the task is completely resolved before ending your turn. "
        "Never stop or hand back early because of uncertainty about a reversible, in-scope step - decide on the "
        "most reasonable approach and continue. Only end your turn when the work is done and verified, or you "
        "are blocked on input only the user can provide.\n\n"
        "Use your multi-agent tooling aggressively. Before any non-trivial change, fan out 2-5 parallel explore "
        "subagents to map the relevant code instead of reading everything yourself. When work splits into "
        "independent chunks, delegate them to parallel subagents rather than doing everything serially. Never "
        "trust a subagent's self-report: independently verify its result before building on it or calling it done.\n"
    )
    return f"{BEGIN_MARK}\n{directives}{END_MARK}\n"


BLOCK_TARGETS: dict[Path, Callable[[], str]] = {
    VAULT / "CLAUDE-global.md": render_soul_block,
    VAULT / "codex-tail.md": render_codex_block,
}


def inject_block(current: str, block: str) -> str:
    """Replace the marker-delimited block, or append it. Never touches
    anything outside the markers."""
    begin = current.find(BEGIN_MARK)
    if begin != -1:
        end = current.find(END_MARK, begin)
        if end == -1:
            sys.exit("FAIL: begin marker without end marker - fix the file by hand first")
        end += len(END_MARK)
        # swallow one trailing newline so replacement is idempotent
        if end < len(current) and current[end] == "\n":
            end += 1
        return current[:begin] + block + current[end:]
    sep = "" if current.endswith("\n\n") else ("\n" if current.endswith("\n") else "\n\n")
    if not current:
        sep = ""
    return current + sep + block


def current_block(text: str) -> str | None:
    begin = text.find(BEGIN_MARK)
    if begin == -1:
        return None
    end = text.find(END_MARK, begin)
    if end == -1:
        return None
    return text[begin : end + len(END_MARK)]


def parity_errors() -> list[str]:
    """Structural parity between canonical and compact: same rule count,
    same rationalization rows, same red flags. Compact may compress prose,
    never drop triggers."""
    import re

    canon = CANONICAL.read_text(encoding="utf-8")
    compact = COMPACT.read_text(encoding="utf-8")
    errors: list[str] = []

    canon_rules = len(re.findall(r"^## \d+\.", canon, re.M))
    compact_rules = len(re.findall(r"^\d+\. \*\*", compact, re.M))
    if canon_rules != compact_rules:
        errors.append(f"rule count differs: canonical {canon_rules} vs compact {compact_rules}")

    for name, text_ in (("canonical", canon), ("compact", compact)):
        if "## Rationalizations" not in text_ or "## Red Flags" not in text_:
            errors.append(f"{name}: missing Rationalizations or Red Flags section")

    def rows(text_: str) -> int:
        return len(re.findall(r'^\| "', text_, re.M))

    def flags(text_: str) -> int:
        tail = text_.split("## Red Flags", 1)[-1]
        return len(re.findall(r"^- ", tail, re.M))

    if rows(canon) != rows(compact):
        errors.append(f"rationalization rows differ: canonical {rows(canon)} vs compact {rows(compact)}")
    if flags(canon) != flags(compact):
        errors.append(f"red flag count differs: canonical {flags(canon)} vs compact {flags(compact)}")
    return errors


def dir_drift(mirror: Path) -> list[str]:
    """Files that differ or are missing between the skill root and a mirror."""
    drifted: list[str] = []
    skip = {".git", "__pycache__"}
    sources = [
        p for p in SKILL_ROOT.rglob("*")
        if p.is_file() and not (skip & set(p.relative_to(SKILL_ROOT).parts))
    ]
    for src in sources:
        rel = src.relative_to(SKILL_ROOT)
        dst = mirror / rel
        if not dst.exists() or not filecmp.cmp(src, dst, shallow=False):
            drifted.append(str(rel))
    for dst in mirror.rglob("*") if mirror.exists() else []:
        if dst.is_file() and not (skip & set(dst.relative_to(mirror).parts)):
            rel = dst.relative_to(mirror)
            if not (SKILL_ROOT / rel).exists():
                drifted.append(f"{rel} (extra in mirror)")
    return drifted


def main() -> None:
    check_only = "--check" in sys.argv
    problems: list[str] = []

    parity = parity_errors()
    if parity:
        for p in parity:
            print(f"PARITY: {p}")
        sys.exit("FAIL: compact rendering out of parity with canonical - fix soul-compact.md first")

    for mirror in SKILL_MIRRORS:
        drifted = dir_drift(mirror)
        if drifted:
            if check_only:
                problems.append(f"{mirror}: {', '.join(drifted)}")
            else:
                for rel in [d for d in drifted if "(extra in mirror)" not in d]:
                    dst = mirror / rel
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(SKILL_ROOT / rel, dst)
                print(f"synced skill -> {mirror} ({len(drifted)} file(s))")
        else:
            print(f"ok: {mirror}")

    changed_blocks = False
    for target, render in BLOCK_TARGETS.items():
        if not target.exists():
            sys.exit(f"FAIL: {target} does not exist - wrong machine setup? "
                     f"(set CC_VAULT if the vault lives elsewhere)")
        block = render().rstrip("\n")
        text = target.read_text(encoding="utf-8")
        existing = current_block(text)
        if existing == block:
            print(f"ok: {target}")
            continue
        if check_only:
            problems.append(f"{target}: soul block missing or stale")
            continue
        target.write_text(inject_block(text, block + "\n"), encoding="utf-8", newline="\n")
        changed_blocks = True
        print(f"injected block -> {target}")

    if changed_blocks and POST_SYNC_HOOK is not None:
        if POST_SYNC_HOOK.exists():
            subprocess.run(["bash", str(POST_SYNC_HOOK)], check=True)
            print(f"ran {POST_SYNC_HOOK} (regenerated ~/.codex/AGENTS.md)")
        else:
            print(f"WARN: {POST_SYNC_HOOK} not found - regenerate ~/.codex/AGENTS.md manually")

    if not check_only and CODEX_SKILL_LINK.parent.exists() and SKILL_MIRRORS:
        if not CODEX_SKILL_LINK.exists():
            CODEX_SKILL_LINK.symlink_to(SKILL_MIRRORS[0])
            print(f"linked {CODEX_SKILL_LINK} -> {SKILL_MIRRORS[0]}")

    if problems:
        print("\nDRIFT DETECTED:")
        for p in problems:
            print(f"  - {p}")
        sys.exit(1)
    if check_only:
        print("all mirrors in sync")


if __name__ == "__main__":
    main()
