"""Sync the canonical soul to all mirrors, or check for drift.

Usage (from the fable-soul skill root):
    python scripts/sync_soul.py          # sync everything
    python scripts/sync_soul.py --check  # report drift, change nothing
"""
from __future__ import annotations

import filecmp
import shutil
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[1]
CANONICAL = SKILL_ROOT / "references" / "soul.md"
HOME = Path.home()

SKILL_MIRRORS = [
    HOME / ".claude" / "skills" / "fable-soul",
    HOME / ".codex" / "skills" / "fable-soul",
]

# Global files = target-specific header + soul body (from the "spirit" line onward).
BODY_MARKER = "**Violating the letter"

GLOBAL_TARGETS = {
    HOME / ".claude" / "CLAUDE.md": (
        "# Global Judgment Rules\n\n"
        "These rules apply to every task in every session. They define HOW to think, not WHAT to do.\n"
        "Source of truth: the fable-soul skill (`~/.claude/skills/fable-soul/references/soul.md`).\n"
        "Do not edit this file directly - edit canonical and run sync_soul.py.\n\n"
    ),
    HOME / ".codex" / "AGENTS.md": (
        "# Global Judgment Rules\n\n"
        "These rules apply to every task in every session. They define HOW to think, not WHAT to do.\n"
        "Source of truth: the fable-soul skill (`~/.codex/skills/fable-soul/references/soul.md`).\n"
        "Do not edit this file directly - edit canonical and run sync_soul.py.\n\n"
    ),
}


def soul_body() -> str:
    text = CANONICAL.read_text(encoding="utf-8")
    idx = text.find(BODY_MARKER)
    if idx == -1:
        sys.exit(f"FAIL: body marker {BODY_MARKER!r} not found in {CANONICAL}")
    return text[idx:]


def render_global(header: str) -> str:
    return header + soul_body()


def dir_drift(mirror: Path) -> list[str]:
    """Files that differ or are missing between the skill root and a mirror."""
    drifted: list[str] = []
    sources = [p for p in SKILL_ROOT.rglob("*") if p.is_file() and "__pycache__" not in p.parts]
    for src in sources:
        rel = src.relative_to(SKILL_ROOT)
        dst = mirror / rel
        if not dst.exists() or not filecmp.cmp(src, dst, shallow=False):
            drifted.append(str(rel))
    for dst in mirror.rglob("*") if mirror.exists() else []:
        if dst.is_file() and "__pycache__" not in dst.parts:
            rel = dst.relative_to(mirror)
            if not (SKILL_ROOT / rel).exists():
                drifted.append(f"{rel} (extra in mirror)")
    return drifted


def main() -> None:
    check_only = "--check" in sys.argv
    problems: list[str] = []

    for mirror in SKILL_MIRRORS:
        drifted = dir_drift(mirror)
        if drifted:
            if check_only:
                problems.append(f"{mirror}: {', '.join(drifted)}")
            else:
                for rel in [d for d in drifted if "(extra in mirror)" not in d]:
                    dst = mirror / rel
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(SKILL_ROOT / rel, dst)
                print(f"synced skill -> {mirror} ({len(drifted)} file(s))")
        else:
            print(f"ok: {mirror}")

    for target, header in GLOBAL_TARGETS.items():
        expected = render_global(header)
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current and not current.startswith("# Global Judgment Rules"):
            print(f"SKIPPED {target}: existing content not generated by this script. "
                  f"Merge the soul body manually or remove the file first.")
            continue
        if current != expected:
            if check_only:
                problems.append(f"{target}: body or header differs from canonical")
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(expected, encoding="utf-8", newline="\n")
                print(f"regenerated {target}")
        else:
            print(f"ok: {target}")

    if problems:
        print("\nDRIFT DETECTED:")
        for p in problems:
            print(f"  - {p}")
        sys.exit(1)
    if check_only:
        print("all mirrors in sync")


if __name__ == "__main__":
    main()
